[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "just-agents-coding"
version = "0.3.8"
description = "Just Agents - Coding Components"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Alex Karmazin", email = "karmazinalex@gmail.com" },
    { name = "Anton Kulaga", email = "antonkulaga@gmail.com" },
    { name = "Newton Winter", email = "isoutthere@gmail.com" },
]
maintainers = [
    { name = "Anton Kulaga", email = "antonkulaga@gmail.com" },
    { name = "Newton Winter", email = "isoutthere@gmail.com" },
]
dependencies = [
    "just-agents-core>=0.3.8",
    "llm-sandbox>=0.1.4",
]
license = {text = "MIT"}

[tool.setuptools.packages.find]
where = ["."]
include = ["just_agents", "just_agents.*"]
exclude = [
    "logs*",
    "output*", 
    "*.egg-info",
    "build",
    "dist"
]

[tool.setuptools.package-data]
"config" = ["*.yaml", "*.yml"]
"just_agents" = ["*.yaml", "*.yml"]